import numpy as np
import matplotlib.pyplot as plt
x = np.linspace (0 ,10)
fx = np.exp(-x/10)*np.sin(np.pi*x)
gx = x* np.exp(-x/3)
fig, ax=plt.subplots()
ax.plot(x, fx , label='f(x)')
ax.plot (x, gx , label = 'g(x)')

teta = np.linspace (0 , 2*np.pi)
r0 = 0.8 + np.cos (teta)
r1 = 1.0 + np.cos (teta)
r2 = 1.2 + np.cos (teta)
x0 = r0 * np.cos (teta)
y0 = r0 * np.sin (teta)
x1 = r1 * np.cos (teta)
y1 = r1 * np.sin (teta)
x2 = r2 * np.cos (teta)
y2 = r2 * np.sin (teta)
fig, ay =plt.subplots()
ay.plot(x0 , y0 , label = 'r=0.8')
ay.plot(x1 , y1 , label = 'r=1.0')
ay.plot(x2 , y2 , label = 'r=1.2')
leg1 = ay.legend()
plt.xlabel ('x')
plt.ylabel('y')
plt.show()
